export const types =  {

    GETDATA: '[GAMES] games',
    GETHEROBYID: '[HERO-ID] heroId',
    ORDERBYPOWERINTELLIGENCE: '[INTELLIGENCE] intelligence',
    ORDERBYPOWERSTRENGTH: '[STRENGTH] strength',
    ORDERBYPOWERSPEED: '[SPEED] speed',
    ORDERBYPOWERDURABILITY: '[DURABILITY] durability',
    ORDERBYPOWERPOWER: '[POWER] power',
    ORDERBYPOWERCOMBAT: '[COMBAT] combat',
    ORDERBYALPHABET: '[ALPHABET] alphabet',
    ADDAPPEARANCE: '[ADDAPA] addapp',
    ADDERROR: '[ERROR] error'

};
